config/routes.rb
MicamoveRails::Application.routes.draw do
  resources :stores


  resources :visuals
  resources :team_members, :path => "co-op"
  resources :products

  get "/watches" => "products#watches"
  get "/clothing" => "products#clothing"
  get "/sable-collection" => "products#sable"
  get "/blonde-collection" => "products#blonde"


  get "/team" => "pages#team"
  get "/visuals" => "pages#visuals"
  get "/support" => "pages#support", as: 'support_page'
  get "/thank-you-sticker-pack" => "pages#stickerthanks"
  get "/registration-thank-you" => "pages#registration_thankyou"
  get "/email-thank-you" => "pages#emailthanks"
  get "/purchase-thank-you" => "pages#purchasethanks"
  get "/contact-us-thank-you" => "pages#contactthanks"
  root to: 'pages#home'

  get "/index" => "pages#index"
  get "/store" => "pages#store"
  get "/team" => "pages#team"
  get "/clothes" => "pages#clothing"
  get "/wood-watch" => "pages#woodWatches"
  get "/wood-watches-mens" => "pages#woodWatchesMen"
  get "/mens-watches" => "pages#mensWatches"
  get "/the-baron-rose-wooden-watch" => "pages#baronRoseWatch"
  # get "/products/the-official" => "pages#theTree"
  # get "/products/the-blitzen" => "pages#theBlitzen"
  # get "/products/the-albuquerque" => "pages#theAlbuquerque"
  get "/the-baron-black-teal-wood-watch" => "pages#baronBlackWatch"
  get "/the-baron-silver-wooden-watch" => "pages#baronSilverWatch"
  get "/the-drift-brown-gold-wood-watch" => "pages#driftbrownWatch"
  get "/return-policy" => "pages#returnPolicy"
  get "/warranty" => "pages#warranty"
  get "/dealer-locator" => "pages#dealerLocator"

  devise_for :admins, :controllers => { :sessions => "admin_session" }
end

app/models/visual.rb
class Visual < ActiveRecord::Base
  attr_accessible :embedcode, :name, :url, :thumbnail

  extend FriendlyId
  friendly_id :url

end

app/controllers/visuals_controller.rb
class VisualsController < ApplicationController
  # GET /visuals
  # GET /visuals.json
  def index
    @visuals = Visual.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @visuals }
    end
  end

  # GET /visuals/1
  # GET /visuals/1.json
  def show
    @visualList = Visual.all
    @visual = Visual.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @visual }
    end
  end

  # GET /visuals/new
  # GET /visuals/new.json
  def new
    @visual = Visual.new
    redirect_to @visual

    # respond_to do |format|
    #   format.html # new.html.erb
    #   format.json { render json: @visual }
    # end
  end

  # GET /visuals/1/edit
  def edit
    @visual = Visual.find(params[:id])
    redirect_to @visual
  end

  # POST /visuals
  # POST /visuals.json
  def create
    @visual = Visual.new(params[:visual])

    respond_to do |format|
      if @visual.save
        format.html { redirect_to @visual, notice: 'Visual was successfully created.' }
        format.json { render json: @visual, status: :created, location: @visual }
      else
        format.html { render action: "new" }
        format.json { render json: @visual.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /visuals/1
  # PUT /visuals/1.json
  def update
    @visual = Visual.find(params[:id])

    respond_to do |format|
      if @visual.update_attributes(params[:visual])
        format.html { redirect_to @visual, notice: 'Visual was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @visual.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visuals/1
  # DELETE /visuals/1.json
  def destroy
    @visual = Visual.find(params[:id])
    @visual.destroy

    respond_to do |format|
      format.html { redirect_to visuals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/visuals_helper.rb
module VisualsHelper
end

app/views/visuals/_form.html.erb
<%= form_for(@visual) do |f| %>
  <% if @visual.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visual.errors.count, "error") %> prohibited this visual from being saved:</h2>

      <ul>
      <% @visual.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :embedcode %><br />
    <%= f.text_field :embedcode %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visuals/_visual-show-nav.html.erb
		<div class="row-fluid sub-nav">
      <div class="page-title"><a href="/visuals"><%= @visual.name %></a></div>
    </div>

    <div class="row-fluid sub-nav-mobile">
      <div class="span7 sub-nav-item"><a id="" href="/visuals"><%= @visual.name %> <!-- <span class="caret"></span> --></a></div>
      <div class="span5 sub-nav-item"></div>
    </div>

    <div class="row-fluid sub-mobile-drop" id="opensubNav">
      <div class="span12">
      	<div class="sub-item-drop"><a href="#">Recent</a></div>
      	<div class="sub-item-drop"><a href="#">Popular</a></div>
      </div>
    </div>

<script>
	$(document).ready(function() {
		$('#subNavOpen').click(function() {
		  $('#opensubNav').slideToggle('fast', function() {
		    // Animation complete.
		  });
		});
	});
</script>

app/views/visuals/_visuals-nav.html.erb
		<div class="row-fluid sub-nav">
      <div class="page-title"><a href="/visuals">Videos</a></div>
      <!-- <div class="sub-nav-item"><a href="#">Recent</a></div>
      <div class="sub-nav-item"><a href="#">Popular</a></div> -->
    </div>

    <div class="row-fluid sub-nav-mobile">
      <div class="span7 sub-nav-item"><a id="" href="/visuals">Videos <!-- <span class="caret"></span> --></a></div>
      <div class="span5 sub-nav-item"></div>
    </div>

    <div class="row-fluid sub-mobile-drop" id="opensubNav">
      <div class="span12">
      	<div class="sub-item-drop"><a href="#">Recent</a></div>
      	<div class="sub-item-drop"><a href="#">Popular</a></div>
      </div>
    </div>

<script>
	$(document).ready(function() {
		$('#subNavOpen').click(function() {
		  $('#opensubNav').slideToggle('fast', function() {
		    // Animation complete.
		  });
		});
	});
</script>

app/views/visuals/edit.html.erb
<% meta_description "Edit" %>

<h1>Editing visual</h1>

<%= render 'form' %>

<%= link_to 'Show', @visual %> |
<%= link_to 'Back', visuals_path %>

app/views/visuals/index.html.erb
<% content_for :title, "Visuals | Mica Watches | Wood Watch Collections" %>
<% meta_description "Check out the latest edits from Mica Minutes to the OpenMind project." %>

<div id="content-container">

  <div class="container-fluid sub-nav-container">
    <%= render(:partial => "visuals-nav") %>
  </div>

  <div class="container-fluid visuals">
    <div class="row-fluid" id="visualTiles">
      <div class="span12">
        <div class="visual-images">
          <% @visuals.each do |visual| %>
          <div class="visual-image">
            <%= link_to image_tag(visual.thumbnail), visual %>
            <%= link_to image_tag("/assets/player-button.png"), visual, :class => 'play' %>
            <h5><%= link_to visual.name, visual %></h5>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>


<script>

$(document).ready(function() {

  $('.visuals-nav').addClass('active-nav-item');

  $('.visuals').fadeIn(1000);

  var $container = $('.visual-images');
  $container.imagesLoaded(function(){
    $container.masonry({
      itemSelector : '.visual-image',
      columnWidth : 220, 
      gutterWidth : 20, 
      isFitWidth : true
    });
  });
});

</script>

app/views/visuals/new.html.erb
<% meta_description "New" %>

<h1>New visual</h1>

<%= render 'form' %>

<%= link_to 'Back', visuals_path %>

app/views/visuals/show.html.erb
<% content_for :title, "#{@visual.name} | Mica Watches | Wood Watch Collections" %>
<% meta_description "Check out the latest edits from Mica Minutes to the OpenMind project." %>

<div id="content-container">

  <div class="container-fluid sub-nav-container">
    <%= render(:partial => "visual-show-nav") %>
  </div>

  <div class="container-fluid visuals">

  	<div class="row-fluid">
			<div class="span12 visual-header">
        <div class="video-player active">
         <iframe src="<%= @visual.embedcode %>" width="940" height="528" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe> 
        </div>
      </div>
    </div>

    <div class="row-fluid" id="visualTiles">
      <div class="span12">
        <div class="visual-images">
          <% @visualList.each do |visual| %>
          <div class="visual-image">
            <%= link_to image_tag(visual.thumbnail), visual %>
            <%= link_to image_tag("/assets/player-button.png"), visual, :class => 'play' %>
            <h5><%= link_to visual.name, visual %></h5>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>


<script>
$(document).ready(function() {

  $('.visual-images').fadeIn(1000);

  $('.visuals-nav').addClass('active-nav-item');

  var $container = $('.visual-images');
  $container.imagesLoaded(function(){
    $container.masonry({
      itemSelector : '.visual-image',
      columnWidth : 220, 
      gutterWidth : 20, 
      isFitWidth : true
    });
  });


});



</script>