config/routes.rb
MicamoveRails::Application.routes.draw do
  resources :stores


  resources :visuals
  resources :team_members, :path => "co-op"
  resources :products

  get "/watches" => "products#watches"
  get "/clothing" => "products#clothing"
  get "/sable-collection" => "products#sable"
  get "/blonde-collection" => "products#blonde"


  get "/team" => "pages#team"
  get "/visuals" => "pages#visuals"
  get "/support" => "pages#support", as: 'support_page'
  get "/thank-you-sticker-pack" => "pages#stickerthanks"
  get "/registration-thank-you" => "pages#registration_thankyou"
  get "/email-thank-you" => "pages#emailthanks"
  get "/purchase-thank-you" => "pages#purchasethanks"
  get "/contact-us-thank-you" => "pages#contactthanks"
  root to: 'pages#home'

  get "/index" => "pages#index"
  get "/store" => "pages#store"
  get "/team" => "pages#team"
  get "/clothes" => "pages#clothing"
  get "/wood-watch" => "pages#woodWatches"
  get "/wood-watches-mens" => "pages#woodWatchesMen"
  get "/mens-watches" => "pages#mensWatches"
  get "/the-baron-rose-wooden-watch" => "pages#baronRoseWatch"
  # get "/products/the-official" => "pages#theTree"
  # get "/products/the-blitzen" => "pages#theBlitzen"
  # get "/products/the-albuquerque" => "pages#theAlbuquerque"
  get "/the-baron-black-teal-wood-watch" => "pages#baronBlackWatch"
  get "/the-baron-silver-wooden-watch" => "pages#baronSilverWatch"
  get "/the-drift-brown-gold-wood-watch" => "pages#driftbrownWatch"
  get "/return-policy" => "pages#returnPolicy"
  get "/warranty" => "pages#warranty"
  get "/dealer-locator" => "pages#dealerLocator"

  devise_for :admins, :controllers => { :sessions => "admin_session" }
end

app/models/store.rb
class Store < ActiveRecord::Base
  attr_accessible :address, :city, :latitude, :longitude, :phone_number, :state, :store_name, :zip

  geocoded_by :full_address
  after_validation :geocode, :if => :address_changed?

  def full_address
    "#{address} #{city}, #{state} #{zip}"
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  layout 'admin'
  before_filter :authenticate_admin!

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stores }
    end
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @store = Store.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/new
  # GET /stores/new.json
  def new
    @store = Store.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/1/edit
  def edit
    @store = Store.find(params[:id])
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(params[:store])

    respond_to do |format|
      if @store.save
        format.html { redirect_to stores_path, notice: 'Store was successfully created.' }
        format.json { render json: @store, status: :created, location: @store }
      else
        format.html { render action: "new" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stores/1
  # PUT /stores/1.json
  def update
    @store = Store.find(params[:id])

    respond_to do |format|
      if @store.update_attributes(params[:store])
        format.html { redirect_to stores_path, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store = Store.find(params[:id])
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :store_name %><br />
    <%= f.text_field :store_name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit :class=> 'btn btn-info' %> &nbsp;
    <%= link_to 'Back', stores_path, :class => 'btn btn-info' %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

app/views/stores/index.html.erb
<style type="text/css">
    #map_wrapper {
        height: 400px;
    }

    #map_canvas {
        width: 100%;
        height: 100%;
    }
</style>

<h1>Stores</h1>

<%= link_to 'Add Store', new_store_path %>

<table class="table">
  <thead>
  <tr>
    <th>Store name</th>
    <th>Address</th>
    <th>Phone number</th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @stores.each do |store| %>
      <tr>
        <td><%= store.store_name %></td>
        <td><%= store.full_address %></td>
        <td><%= store.phone_number %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<div id="map_wrapper">
  <div id="map_canvas" class="mapping"></div>
</div>
<script type="text/javascript">
    var markers = [
        <% @stores.each do |store| %>
        [ '<%=store.full_address%>', <%= store.latitude %> , <%= store.longitude %> ],
        <% end %>
    ];

    var infoWindowContent = [
        <% @stores.each do |store| %>
        [ '<div class="info_content">' +
                '<h4><nobr><%=store.store_name%><nobr></h4>' +
                '<div><%= store.address %></div>' +
                '<div><%= store.city %></div>' +
                '<div><%= "#{store.state}, #{store.zip}" %></div>' +
                '<div><%= "#{store.phone_number}" %></div>' +
                '</div>'],
        <% end %>
    ];

    $(document).ready(function () {
        var script = document.createElement('script');
        script.src = "http://maps.googleapis.com/maps/api/js?sensor=false&callback=initialize_map";
        document.body.appendChild(script);
    });
</script>

app/views/stores/new.html.erb
<h1>New store</h1>
<%= render 'form' %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Store name:</b>
  <%= @store.store_name %>
</p>

<p>
  <b>Address:</b>
  <%= @store.address %>
</p>

<p>
  <b>City:</b>
  <%= @store.city %>
</p>

<p>
  <b>State:</b>
  <%= @store.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @store.zip %>
</p>

<p>
  <b>Phone number:</b>
  <%= @store.phone_number %>
</p>

<p>
  <b>Latitude:</b>
  <%= @store.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @store.longitude %>
</p>


<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>