config/routes.rb
MicamoveRails::Application.routes.draw do
  resources :stores


  resources :visuals
  resources :team_members, :path => "co-op"
  resources :products

  get "/watches" => "products#watches"
  get "/clothing" => "products#clothing"
  get "/sable-collection" => "products#sable"
  get "/blonde-collection" => "products#blonde"


  get "/team" => "pages#team"
  get "/visuals" => "pages#visuals"
  get "/support" => "pages#support", as: 'support_page'
  get "/thank-you-sticker-pack" => "pages#stickerthanks"
  get "/registration-thank-you" => "pages#registration_thankyou"
  get "/email-thank-you" => "pages#emailthanks"
  get "/purchase-thank-you" => "pages#purchasethanks"
  get "/contact-us-thank-you" => "pages#contactthanks"
  root to: 'pages#home'

  get "/index" => "pages#index"
  get "/store" => "pages#store"
  get "/team" => "pages#team"
  get "/clothes" => "pages#clothing"
  get "/wood-watch" => "pages#woodWatches"
  get "/wood-watches-mens" => "pages#woodWatchesMen"
  get "/mens-watches" => "pages#mensWatches"
  get "/the-baron-rose-wooden-watch" => "pages#baronRoseWatch"
  # get "/products/the-official" => "pages#theTree"
  # get "/products/the-blitzen" => "pages#theBlitzen"
  # get "/products/the-albuquerque" => "pages#theAlbuquerque"
  get "/the-baron-black-teal-wood-watch" => "pages#baronBlackWatch"
  get "/the-baron-silver-wooden-watch" => "pages#baronSilverWatch"
  get "/the-drift-brown-gold-wood-watch" => "pages#driftbrownWatch"
  get "/return-policy" => "pages#returnPolicy"
  get "/warranty" => "pages#warranty"
  get "/dealer-locator" => "pages#dealerLocator"

  devise_for :admins, :controllers => { :sessions => "admin_session" }
end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
  attr_accessible :bio, :facebook, :industry, :instagram, :masthead_image, :name, :tile_image, :tile_hover, :twitter, :video_embed
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  # GET /team_members
  # GET /team_members.json
  def index
    @team_members = TeamMember.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @team_members }
    end
  end

  # GET /team_members/1
  # GET /team_members/1.json
  def show
    @team_member = TeamMember.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @team_member }
    end
  end

  # GET /team_members/new
  # GET /team_members/new.json
  def new
    @team_member = TeamMember.new
    redirect_to @team_member

    # respond_to do |format|
    #   format.html # new.html.erb
    #   format.json { render json: @team_member }
    # end
  end

  # GET /team_members/1/edit
  def edit
    @team_member = TeamMember.find(params[:id])
    redirect_to @team_member
  end

  # POST /team_members
  # POST /team_members.json
  def create
    @team_member = TeamMember.new(params[:team_member])

    respond_to do |format|
      if @team_member.save
        format.html { redirect_to @team_member, notice: 'Team member was successfully created.' }
        format.json { render json: @team_member, status: :created, location: @team_member }
      else
        format.html { render action: "new" }
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /team_members/1
  # PUT /team_members/1.json
  def update
    @team_member = TeamMember.find(params[:id])

    respond_to do |format|
      if @team_member.update_attributes(params[:team_member])
        format.html { redirect_to @team_member, notice: 'Team member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_members/1
  # DELETE /team_members/1.json
  def destroy
    @team_member = TeamMember.find(params[:id])
    @team_member.destroy

    respond_to do |format|
      format.html { redirect_to team_members_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/views/team_members/_form.html.erb
<%= form_for(@team_member) do |f| %>
  <% if @team_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@team_member.errors.count, "error") %> prohibited this team_member from being saved:</h2>

      <ul>
      <% @team_member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :industry %><br />
    <%= f.text_field :industry %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :instagram %><br />
    <%= f.text_field :instagram %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br />
    <%= f.text_field :facebook %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br />
    <%= f.text_field :twitter %>
  </div>
  <div class="field">
    <%= f.label :masthead_image %><br />
    <%= f.text_field :masthead_image %>
  </div>
  <div class="field">
    <%= f.label :video_embed %><br />
    <%= f.text_area :video_embed %>
  </div>
  <div class="field">
    <%= f.label :tile_image %><br />
    <%= f.text_field :tile_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/team_members/_team-member-nav.html.erb
		<div class="row-fluid sub-nav">
      <div class="page-title"><a href="/co-op"><%= @team_member.name %></a></div>
      <div class="sub-nav-item"><a href="#">All</a></div>
      <div class="sub-nav-item"><a href="#">Snow</a></div>
      <div class="sub-nav-item"><a href="#">Skate</a></div>
      <div class="sub-nav-item"><a href="#">Surf</a></div>
      <div class="sub-nav-item"><a href="#">Craftsman</a></div>
      <div class="sub-nav-item"><a href="#">Art</a></div>
      <div class="sub-nav-item"><a href="#">Music</a></div>

    </div>

    <div class="row-fluid sub-nav-mobile">
      <div class="span7 sub-nav-item"><a id="subNavOpen" href="#"><%= @team_member.name %><span class="caret"></span></a></div>
      <div class="span5 sub-nav-item"></div>
    </div>

    <div class="row-fluid sub-mobile-drop" id="opensubNav">
      <div class="span12">
      	<div class="sub-item-drop"><a href="#">All</a></div>
        <div class="sub-item-drop"><a href="#">Snow</a></div>
        <div class="sub-item-drop"><a href="#">Skate</a></div>
        <div class="sub-item-drop"><a href="#">Surf</a></div>
        <div class="sub-item-drop"><a href="#">Craftsman</a></div>
        <div class="sub-item-drop"><a href="#">Art</a></div>
      	<div class="sub-item-drop"><a href="#">Music</a></div>
      </div>
    </div>

<script>
	$(document).ready(function() {
		$('#subNavOpen').click(function() {
		  $('#opensubNav').slideToggle('fast', function() {
		    // Animation complete.
		  });
		});
	});
</script>

app/views/team_members/_team-nav.html.erb
		<div class="row-fluid sub-nav">
      <div class="page-title"><a href="/co-op">The Co/Op</a></div>
<!--       <div class="sub-nav-item"><a href="#">All</a></div>
      <div class="sub-nav-item"><a href="#">Snow</a></div>
      <div class="sub-nav-item"><a href="#">Skate</a></div>
      <div class="sub-nav-item"><a href="#">Surf</a></div>
      <div class="sub-nav-item"><a href="#">Craftsman</a></div>
      <div class="sub-nav-item"><a href="#">Art</a></div>
      <div class="sub-nav-item"><a href="#">Music</a></div> -->

    </div>

    <div class="row-fluid sub-nav-mobile">
      <div class="span7 sub-nav-item"><a id="" href="/team_members">The Co/Op <!-- <span class="caret"></span> --></a></div>
      <div class="span5 sub-nav-item"></div>
    </div>

    <div class="row-fluid sub-mobile-drop" id="opensubNav">
      <div class="span12">
      	<div class="sub-item-drop"><a href="#">All</a></div>
        <div class="sub-item-drop"><a href="#">Snow</a></div>
        <div class="sub-item-drop"><a href="#">Skate</a></div>
        <div class="sub-item-drop"><a href="#">Surf</a></div>
        <div class="sub-item-drop"><a href="#">Craftsman</a></div>
        <div class="sub-item-drop"><a href="#">Art</a></div>
      	<div class="sub-item-drop"><a href="#">Music</a></div>
      </div>
    </div>

<script>
	$(document).ready(function() {
		$('#subNavOpen').click(function() {
		  $('#opensubNav').slideToggle('fast', function() {
		    // Animation complete.
		  });
		});
	});
</script>

app/views/team_members/edit.html.erb
<% meta_description "Edit" %>

<h1>Editing team_member</h1>

<%= render 'form' %>

<%= link_to 'Show', @team_member %> |
<%= link_to 'Back', team_members_path %>

app/views/team_members/index.html.erb
<% content_for :title, "Co-Op | Mica Watches | Wood Watch Collections" %>
<% meta_description "The riders, artists and craftsman supporting the movement." %>


<div id="content-container">

  <div class="container-fluid sub-nav-container">
    <%= render(:partial => "team-nav") %>
  </div>

  <div id="team-tiles" class="tiled-images container-fluid ">
    <div class="row-fluid"> 
      <div class="span12">
        <div class="masonry-container">
          <% @team_members.each do |team_member| %>
          <div class="team-tile-image">
            <%= div_for team_member, :class => "" do %>
              <%= image_tag(team_member.tile_image) %>
              <%= image_tag(team_member.tile_hover) %>
            <% end %>
            <!-- <div class="main-image"><%=image_tag(team_member.tile_image)%></div>
            <div class="hover-image"><%= image_tag(team_member.tile_hover) %></div> -->
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function() {

    $('.tiled-images').fadeIn(1000);

    // hover states

    $('img[alt="Seth-huot-hover"]').hide()
    $('img[alt="Alex-andrews-hover"]').hide()
    $('img[alt="Charles-bergquist-hover"]').hide()
    $('img[alt="Scott-stevens-hover"]').hide()
    $('img[alt="Mason-dyer-hover"]').hide()
    $('img[alt="Sean-black-hover"]').hide()
    $('img[alt="Cale-zima-hover"]').hide()
    $('img[alt="Jordan-mendenhall-hover"]').hide()

    $('img[alt="Seth-huot"]').mouseover(function () {
      $(this).hide()
      $('img[alt="Seth-huot-hover"]').show()
    });
    $('img[alt="Seth-huot-hover"]').mouseleave(function () {
      $(this).hide()
      $('img[alt="Seth-huot"]').show()
    });

    $('img[alt="Alex-andrews"]').mouseover(function () {
      $(this).hide()
      $('img[alt="Alex-andrews-hover"]').show()
    });
    $('img[alt="Alex-andrews-hover"]').mouseleave(function () {
      $(this).hide()
      $('img[alt="Alex-andrews"]').show()
    });

    $('img[alt="Charles-bergquist"]').mouseover(function () {
      $(this).hide()
      $('img[alt="Charles-bergquist-hover"]').show()
    });
    $('img[alt="Charles-bergquist-hover"]').mouseleave(function () {
      $(this).hide()
      $('img[alt="Charles-bergquist"]').show()
    });

    $('img[alt="Scott-stevens"]').mouseover(function () {
      $(this).hide()
      $('img[alt="Scott-stevens-hover"]').show()
    });
    $('img[alt="Scott-stevens-hover"]').mouseleave(function () {
      $(this).hide()
      $('img[alt="Scott-stevens"]').show()
    });

    $('img[alt="Mason-dyer"]').mouseover(function () {
      $(this).hide()
      $('img[alt="Mason-dyer-hover"]').show()
    });
    $('img[alt="Mason-dyer-hover"]').mouseleave(function () {
      $(this).hide()
      $('img[alt="Mason-dyer"]').show()
    });

    $('img[alt="Sean-black"]').mouseover(function () {
      $(this).hide()
      $('img[alt="Sean-black-hover"]').show()
    });
    $('img[alt="Sean-black-hover"]').mouseleave(function () {
      $(this).hide()
      $('img[alt="Sean-black"]').show()
    });

    $('img[alt="Cale-zima"]').mouseover(function () {
      $(this).hide()
      $('img[alt="Cale-zima-hover"]').show()
    });
    $('img[alt="Cale-zima-hover"]').mouseleave(function () {
      $(this).hide()
      $('img[alt="Cale-zima"]').show()
    });

    $('img[alt="Jordan-mendenhall"]').mouseover(function () {
      $(this).hide()
      $('img[alt="Jordan-mendenhall-hover"]').show()
    });
    $('img[alt="Jordan-mendenhall-hover"]').mouseleave(function () {
      $(this).hide()
      $('img[alt="Jordan-mendenhall"]').show()
    });

    var $container = $('.masonry-container');
    $container.imagesLoaded(function(){
      $container.masonry({
        itemSelector : '.team-tile-image',
        columnWidth : 300, 
        gutterWidth : 20, 
        isFitWidth : true
      });
    });

    $('.team-nav').addClass('active-nav-item');

  });
</script>

app/views/team_members/new.html.erb
<% meta_description "New" %>

<h1>New team_member</h1>

<%= render 'form' %>

<%= link_to 'Back', team_members_path %>

app/views/team_members/show.html.erb
<% meta_description "Show" %>

<div id="content-container">

  <div class="container-fluid sub-nav-container">
    <%= render(:partial => "team-member-nav") %>
  </div>

  <div class="container-fluid team-masthead">
      <div class="row-fluid">
        <div class="span12">
          <img src="<%= @team_member.masthead_image %>">
        </div>
      </div>
  </div>

  <div class="container-fluid team-bio" style="max-width: 940px">
    <div class="row-fluid">
      <div class="span12">
        <p><%= @team_member.bio %></p>
      </div>
    </div>
  </div>

  <div class="container-fluid video" style="max-width: 940px">
    <div class="row-fluid">
      <div class="span12">
        <h3>Videos</h3>
      </div>
    </div>
    <div class="row-fluid" style="max-width: 940px">
      <div class="span12">
        <iframe src="<%= @team_member.video_embed %>" width="940" height="529" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
      </div>
    </div>
  </div>



</div>