config/routes.rb
MicamoveRails::Application.routes.draw do
  resources :stores


  resources :visuals
  resources :team_members, :path => "co-op"
  resources :products

  get "/watches" => "products#watches"
  get "/clothing" => "products#clothing"
  get "/sable-collection" => "products#sable"
  get "/blonde-collection" => "products#blonde"


  get "/team" => "pages#team"
  get "/visuals" => "pages#visuals"
  get "/support" => "pages#support", as: 'support_page'
  get "/thank-you-sticker-pack" => "pages#stickerthanks"
  get "/registration-thank-you" => "pages#registration_thankyou"
  get "/email-thank-you" => "pages#emailthanks"
  get "/purchase-thank-you" => "pages#purchasethanks"
  get "/contact-us-thank-you" => "pages#contactthanks"
  root to: 'pages#home'

  get "/index" => "pages#index"
  get "/store" => "pages#store"
  get "/team" => "pages#team"
  get "/clothes" => "pages#clothing"
  get "/wood-watch" => "pages#woodWatches"
  get "/wood-watches-mens" => "pages#woodWatchesMen"
  get "/mens-watches" => "pages#mensWatches"
  get "/the-baron-rose-wooden-watch" => "pages#baronRoseWatch"
  # get "/products/the-official" => "pages#theTree"
  # get "/products/the-blitzen" => "pages#theBlitzen"
  # get "/products/the-albuquerque" => "pages#theAlbuquerque"
  get "/the-baron-black-teal-wood-watch" => "pages#baronBlackWatch"
  get "/the-baron-silver-wooden-watch" => "pages#baronSilverWatch"
  get "/the-drift-brown-gold-wood-watch" => "pages#driftbrownWatch"
  get "/return-policy" => "pages#returnPolicy"
  get "/warranty" => "pages#warranty"
  get "/dealer-locator" => "pages#dealerLocator"

  devise_for :admins, :controllers => { :sessions => "admin_session" }
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <link href="http://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
  <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
  <script type="text/javascript" src="//use.typekit.net/mdj3cmj.js"></script>
  <script type="text/javascript">stLight.options({publisher: "b1546e77-7fd3-4a0b-a627-d04a25d4abf4", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
  <meta name="viewport" content="width = device-width, initial-scale = 1, maximum-scale = 1">
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body data-spy="scroll" data-target=".subnav" data-offset="50" data-twttr-rendered="true">
<div style="height: 40px;">
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container" xmlns="http://www.w3.org/1999/html">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand">Micamove Admin
          <!--<sup style="font-size: 11px; top: -0.8em;">alpha</sup> -->
        </a>

        <% if admin_signed_in? %>
            <ul class="nav">
              <li class="<%= 'active' if (controller_name=='stores') %>"><%= link_to (content_tag :i, '', :class => '') + ' Stores', stores_path %></li>
            </ul>
            <ul class="nav pull-right">
              <li><%= link_to (content_tag :i, '', :class => 'icon-off icon-black') + ' Sign out', destroy_admin_session_path %></li>
            </ul>
        <% else %>
            <div class="nav-collapse">
              <ul class="nav pull-right">
                <% if (controller_name != 'admin_session') %>
                    <li class="divider-vertical"></li>
                    <li><%= link_to 'Login', new_admin_session_path %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row" style="margin-top: 5px;">
    <div class="span5">
        <span style="vertical-align: middle;">
        <strong><h4><%= yield :form_caption %></h4></strong>
        </span>
    </div>
    <div class="span7">
      <div class="pull-right"><%= yield :form_option %></div>
    </div>
  </div>
  <% if !notice.nil? %>
      <div class="row">
        <div class="span12">
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <%= notice %>
          </div>
        </div>
      </div>
  <% end %>
  <% if !alert.nil? %>
      <div class="row">
        <div class="span12">
          <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <%= alert %>
          </div>
        </div>
      </div>
  <% end %>
  <%= yield %>

  <div id="ajaxLoader" style="position: absolute;z-index: 999;display: block;left: 50%;top: 40%; display: none;;">
    <img src="/assets/ajax-loader.gif" alt="">
  </div>
</div>
<div class="container-fluid">
  <section class="footer">
    <div class="row-fluid">
      <div class="span12">
        <br>
        <br>
        <br>
        <br>
        <br>
      </div>
    </div>
  </section>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= yield(:title) %></title>
	<meta name="description" content="<%= meta_description %>" />
	<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
  <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
  <script type="text/javascript" src="//use.typekit.net/mdj3cmj.js"></script>
	<script type="text/javascript">stLight.options({publisher: "b1546e77-7fd3-4a0b-a627-d04a25d4abf4", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
  <meta name="viewport" content="width = device-width, initial-scale = 1, maximum-scale = 1">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="header-desktop hidden-phone">
		<div class="container-fluid">
			<div class="row-fluid" style="max-width: 940px; margin: 0 auto">
				<div class="span3">
					<div class="logo">
						<a href="/"><img src="/assets/logo@2x.png"></img></a>
					</div>
				</div>
				<div class="span9">
					<ul class="nav-links">
						<li class="nav-item store-nav"><a href="/products">Store</a></li>
						<li class="nav-item team-nav"><a href="/co-op">Co/Op</a></li>
						<li class="nav-item"><a href="http://tumblr.micamove.com/">Mvmnt</a></li>
						<li class="nav-item visuals-nav"><a href="/visuals">Visuals</a></li>
						<li class="nav-item support-nav"><a href="/support"></i> Support</a></li>
						<li class="vr"></li>
						<li class="nav-cart "><a href="https://mica.infusionsoft.com/app/manageCart/showManageOrder"><img src="/assets/cart-icon.png"></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>

	<div class="header-mobile hidden-desktop  hidden-tablet visable-phone">
		<div class="container-fluid">
			<div class="row-fluid mobile-nav-row">
				<div class="span7">
					<div class="logo">
						<a href="/"><img src="/assets/logo.png"></img></a>
					</div>
				</div>
				<div class="span4 pull-right">
					<a href="https://mica.infusionsoft.com/app/manageCart/showManageOrder"><img class="mobile-cart-icon" src="/assets/cart-icon.png"></a>
					<a href="#">
						<div class="nav-menu-icon" id="mobileNavLink">
							<div class="nav-icon-line"></div>
							<div class="nav-icon-line"></div>
							<div class="nav-icon-line"></div>
						</div>
					</a>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span12 mobile-nav-links" id="openNavMenu">
					<a href="/products" class="mobile-nav-item">Store</a>
					<a href="/co-op" class="mobile-nav-item">Co/Op</a>
					<a href="http://tumblr.micamove.com" class="mobile-nav-item">Mvmnt</a>
					<a href="/visuals" class="mobile-nav-item">Visuals</a>
					<a href="/support" class="mobile-nav-item">Support</a>
				</div>
			</div>
		</div>
	</div>

<%= yield %>

<div class="desktop-footer">
	<div clas="container-fluid">
		<div class="row-fluid" style="max-width: 940px; margin: 0 auto;">
			<div class="span12 footer-inner">
				<a href="mailto:info@micamove.com" class="footer-item ">info@micamove.com</a>
				<i class="icon-circle"></i>
				<a href="/" class="footer-item">Home</a>
				<i class="icon-circle"></i>
				<a href="/products" class="footer-item">Store</a>
				<i class="icon-circle"></i>
				<a href="/co-op" class="footer-item">Co/Op</a>
				<i class="icon-circle"></i>
				<a href="http://tumblr.micamove.com/" class="footer-item">Mvmnt</a>
				<i class="icon-circle"></i>
				<a href="/visuals" class="footer-item">Visuals</a>
				<i class="icon-circle"></i>
				<a href="/support" class="footer-item">Support</a>
				<i class="icon-circle"></i>
				<span class="footer-item">© 2009-2015 MICA MOVEMENT</span>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span12">
				<form accept-charset="UTF-8" action="https://mica.infusionsoft.com/app/form/process/3d85728873512e54303473725bb9cec0" class="infusion-form form-horizontal" method="POST">
			    <input name="inf_form_xid" type="hidden" value="3d85728873512e54303473725bb9cec0">
			    <input name="inf_form_name" type="hidden" value="Sign up for newsletter">
			    <input name="infusionsoft_version" type="hidden" value="1.29.3.49">

			    <div class="infusion-field">
		        <label for="inf_field_Email"></label>
		        <input class="newsletter-email inputarea" id="inf_field_Email" name="inf_field_Email" type="text" value="EMAIL UPDATES" onclick="if (this.defaultValue==this.value) this.value=''" onblur="if (this.value=='') this.value=this.defaultValue">
		        <div style="align:right; display: inline-block;" class="infusion-submit">
		        	<input type="submit" class="btnsubmit btn-large btn btn-primary" value="Submit">
		      	</div>
			    </div>
				</form>
			</div>
		</div>
		<div class="row-fluid social">
			<div class="span12 ">
				<span class='st_facebook_hcount' displayText='Facebook'></span>
				<span class='st_twitter_hcount' displayText='Tweet'></span>
				<span class='st_pinterest_hcount' displayText='Pinterest'></span>
			</div>
		</div>
	</div>
</div>


	<script type="text/javascript" src="https://mica.infusionsoft.com/app/webTracking/getTrackingCode?trackingId=1787ed0cbc0de166c6048871f5127d21"></script>

  <script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-8288997-1']);
	  _gaq.push(['_trackPageview']);
	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>

</body>


<script>
	$(document).ready(function() {
		$('#mobileNavLink').click(function() {
		  $('#openNavMenu').slideToggle('fast', function() {
		    // Animation complete.
		  });
		});

//testing
        <!--<% if controller_name != 'pages' && action_name != 'home' %>-->
//        if($.cookie('display_offer') == undefined)
//        {
//            $.facybox({
//
//                image: '/assets/lightbox-image500x621.jpg',
//                centerOnScroll: true,
//                onComplete: function(){
//                }
//            });
//            setTimeout(function()
//            {
//                $.facybox.centralize();
//                $("#facybox .footer").click(function() {
//                    window.location.href = '/products';
//                });
//                $("#facybox .body .popup .image img").click(function() {
//                    window.location.href = '/products';
//                });
//            }, 1000);
//            $.cookie('display_offer', '1', {path: '/'}); //, { path: window.location.pathname });
//            //$.fancybox.center(true);
//        }
        <!--<% end %>-->
	});
</script>
</html>